ALTER TABLE public.shas_plans
  ADD COLUMN IF NOT EXISTS unit TEXT NOT NULL DEFAULT 'daf',
  ADD COLUMN IF NOT EXISTS current_amud SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS current_half SMALLINT NOT NULL DEFAULT 1;